services:
  web: 
    build:
      context: app
      target: builder
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports: 
      - "8000:8000"
