# Generated by Django 4.1.7 on 2023-05-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('cost', models.BigIntegerField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('picture_id', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupID', to='Group.group')),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='buy.buy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID_cons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyers', to='buy.buy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID_buy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
