name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: JetBrains/qodana-action@v2023.1.0
       with:
          paths: 'Enigma/Group'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}         